import os

DIAMOND_FILE_ROOT_DIR = os.environ['DIAMOND_FILE_ROOT_DIR']
DIAMOND_EXECUTABLE_PATH = os.environ['DIAMOND_EXECUTABLE_PATH']
STRING_LINKS_PATH = os.environ['STRING_LINKS_PATH']
STRING_ENRICHMENT_PATH = os.environ['STRING_ENRICHMENT_PATH']
OBO_FILE_PATH = os.environ['OBO_FILE_PATH']
GROUND_TRUTH_PATH = os.environ['GROUND_TRUTH_PATH']